# Generated by Django 4.2.7 on 2025-09-26 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=300)),
                ('documento', models.FileField(blank=True, null=True, upload_to='notificaciones/respuestas/')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('revisada_admin', models.BooleanField(default=False)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='notificaciones.notificacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta a Notificación',
                'verbose_name_plural': 'Respuestas a Notificaciones',
                'ordering': ['-fecha_respuesta'],
            },
        ),
    ]
