# Generated by Django 4.2.7 on 2025-10-08 18:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recursos_humanos', '0006_puesto_superior'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=8, help_text='Coordenada de latitud GPS', max_digits=12, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=8, help_text='Coordenada de longitud GPS', max_digits=12, verbose_name='Longitud')),
                ('precision', models.FloatField(blank=True, help_text='Precisión del GPS en metros', null=True, verbose_name='Precisión')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10, verbose_name='Tipo de registro')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ubicacion', to='recursos_humanos.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Registro de Ubicación',
                'verbose_name_plural': 'Registros de Ubicación',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='registroubicacion',
            constraint=models.UniqueConstraint(condition=models.Q(('timestamp__date', models.F('timestamp__date'))), fields=('empleado', 'tipo'), name='unique_registro_per_day'),
        ),
    ]
