# Generated by Django 4.2.7 on 2025-10-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registroubicacion',
            name='unique_registro_per_day',
        ),
        migrations.AddIndex(
            model_name='registroubicacion',
            index=models.Index(fields=['empleado', 'tipo', 'timestamp'], name='ubicaciones_emplead_38e2b8_idx'),
        ),
        migrations.AddIndex(
            model_name='registroubicacion',
            index=models.Index(fields=['timestamp'], name='ubicaciones_timesta_495b64_idx'),
        ),
    ]
