# Generated by assistant to add `fecha` field and unique constraint
from django.db import migrations, models


def populate_fecha(apps, schema_editor):
    Registro = apps.get_model('ubicaciones', 'RegistroUbicacion')
    for r in Registro.objects.all():
        # Usar la fecha del timestamp almacenado
        try:
            r.fecha = r.timestamp.date()
            r.save(update_fields=['fecha'])
        except Exception:
            # En caso de datos corruptos, asignar la fecha actual
            r.fecha = None
            r.save(update_fields=['fecha'])


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0002_remove_registroubicacion_unique_registro_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroubicacion',
            name='fecha',
            field=models.DateField(editable=False, null=True, verbose_name='Fecha'),
        ),
        migrations.RunPython(populate_fecha, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='registroubicacion',
            name='fecha',
            field=models.DateField(editable=False, verbose_name='Fecha'),
        ),
        migrations.AddConstraint(
            model_name='registroubicacion',
            constraint=models.UniqueConstraint(fields=('empleado', 'tipo', 'fecha'), name='unique_registro_per_day'),
        ),
    ]
