# Generated by assistant to add `fecha` field and unique constraint
from django.db import migrations, models


def populate_fecha(apps, schema_editor):
    Registro = apps.get_model('ubicaciones', 'RegistroUbicacion')
    for r in Registro.objects.all():
        # Usar la fecha del timestamp almacenado
        try:
            r.fecha = r.timestamp.date()
            r.save(update_fields=['fecha'])
        except Exception:
            # En caso de datos corruptos, asignar la fecha actual
            r.fecha = None
            r.save(update_fields=['fecha'])


def deduplicate_registros_por_dia(apps, schema_editor):
    """Eliminar registros duplicados por (empleado, tipo, fecha).

    Mantener el registro con el menor `timestamp` (primero del día) y eliminar los demás.
    """
    Registro = apps.get_model('ubicaciones', 'RegistroUbicacion')
    # Recorremos ordenados para conservar el primero por grupo
    seen = set()
    ids_para_eliminar = []
    qs = Registro.objects.all().order_by('empleado_id', 'tipo', 'fecha', 'timestamp')
    for r in qs.iterator():
        key = (r.empleado_id, r.tipo, r.fecha)
        if key in seen:
            ids_para_eliminar.append(r.id)
        else:
            seen.add(key)

    if ids_para_eliminar:
        # Eliminación en batch
        Registro.objects.filter(id__in=ids_para_eliminar).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0002_remove_registroubicacion_unique_registro_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroubicacion',
            name='fecha',
            field=models.DateField(editable=False, null=True, verbose_name='Fecha'),
        ),
        migrations.RunPython(populate_fecha, reverse_code=migrations.RunPython.noop),
        # Limpiar duplicados antes de forzar null=False y crear la constraint única
        migrations.RunPython(deduplicate_registros_por_dia, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='registroubicacion',
            name='fecha',
            field=models.DateField(editable=False, verbose_name='Fecha'),
        ),
        migrations.AddConstraint(
            model_name='registroubicacion',
            constraint=models.UniqueConstraint(fields=('empleado', 'tipo', 'fecha'), name='unique_registro_per_day'),
        ),
    ]
