# Generated by Django 4.2.7 on 2025-10-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0003_add_fecha_and_unique'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='registroubicacion',
            index=models.Index(fields=['fecha'], name='ubicaciones_fecha_a625c6_idx'),
        ),
    ]
