# Generated by Django 4.2.7 on 2025-11-11 18:55

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0016_asignacionportrabajador_empresa_and_more'),
        ('ubicaciones', '0005_merge_fix_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanaLaboralEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField(verbose_name='Semana (inicio - Lunes)')),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Horas trabajadas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semanas_laborales', to='recursos_humanos.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Semana laboral por empleado',
                'verbose_name_plural': 'Semanas laborales por empleado',
                'unique_together': {('empleado', 'semana_inicio')},
            },
        ),
    ]
