# Generated by Django 4.2.7 on 2025-11-11 19:03

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0006_semanalaboralempleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanaLaboralDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('entrada', models.DateTimeField(blank=True, null=True, verbose_name='Entrada')),
                ('salida', models.DateTimeField(blank=True, null=True, verbose_name='Salida')),
                ('horas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Horas')),
                ('semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='ubicaciones.semanalaboralempleado', verbose_name='Semana laboral')),
            ],
            options={
                'verbose_name': 'Día laboral',
                'verbose_name_plural': 'Días laborales',
                'ordering': ['fecha'],
                'unique_together': {('semana', 'fecha')},
            },
        ),
    ]
