# Generated by Django 4.2.7 on 2025-09-24 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0004_remove_empleado_departamento'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departamento',
        ),
    ]
