# Generated by Django 4.2.7 on 2025-09-24 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_delete_departamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sucursal',
        ),
    ]
