# Generated by Django 4.2.7 on 2025-09-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_delete_sucursal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='email',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='razon_social',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='rfc',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='sitio_web',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='telefono',
        ),
    ]
