# Generated by Django 4.2.7 on 2025-09-24 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_alter_empresa_options_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'El teléfono debe contener exactamente 10 dígitos.')], verbose_name='Teléfono'),
        ),
    ]
