# Generated by Django 4.2.7 on 2025-10-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_alter_contacto_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
