# Generated by Django 4.2.7 on 2025-10-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_contacto_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='ACTIVA'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Empresa'),
        ),
    ]
