# Generated by Django 4.2.7 on 2025-11-11 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_alter_empresa_activa_alter_empresa_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.IntegerField(default=0, verbose_name='Proveedor')),
                ('mo_soma', models.IntegerField(default=0, verbose_name='MO SOMA')),
                ('otros_materiales', models.IntegerField(default=0, verbose_name='Otros materiales')),
                ('porcentaje_pu', models.DecimalField(decimal_places=3, default=1.25, max_digits=6, verbose_name='Porcentaje PU')),
                ('pu', models.IntegerField(default=0, verbose_name='PU')),
                ('total_pu', models.IntegerField(default=0, verbose_name='TOTAL PU')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctzs', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'CTZ',
                'verbose_name_plural': 'CTZs',
            },
        ),
    ]
