# Generated by Django 4.2.7 on 2025-11-13 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_ctz'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTZItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('proveedor', 'Proveedor'), ('mo_soma', 'MO SOMA'), ('otros_materiales', 'Otros materiales')], max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('cantidad', models.IntegerField(default=0)),
                ('ctz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='empresas.ctz')),
            ],
            options={
                'verbose_name': 'Ítem CTZ',
                'verbose_name_plural': 'Ítems CTZ',
            },
        ),
    ]
