# Generated by Django 4.2.7 on 2025-11-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_ctzitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctz',
            name='id_manual',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID'),
        ),
    ]
