# Generated by Django 4.2.7 on 2025-11-19 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0011_ctz_id_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTZFormato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partida', models.CharField(max_length=100, verbose_name='Partida')),
                ('concepto', models.TextField(verbose_name='Concepto')),
                ('cantidad', models.DecimalField(decimal_places=3, default=1, max_digits=12, verbose_name='Cantidad')),
                ('unidad', models.CharField(blank=True, max_length=30, verbose_name='Unidad')),
                ('pu', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='PU')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ctz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formatos', to='empresas.ctz', verbose_name='CTZ')),
            ],
            options={
                'verbose_name': 'CTZ Formato',
                'verbose_name_plural': 'CTZs Formato',
            },
        ),
    ]
