# Generated by Django 4.2.7 on 2025-11-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0013_preserve_total_and_add_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctzformato',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='IVA'),
        ),
        migrations.AlterField(
            model_name='ctzformato',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='ctzformato',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='TOTAL'),
        ),
    ]
