# Generated by Django 4.2.7 on 2025-11-20 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0017_merge_0015_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTZFormatoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('pu', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ctz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.ctz')),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='empresas.ctzformato')),
            ],
            options={
                'verbose_name': 'Detalle CTZ Formato',
                'verbose_name_plural': 'Detalles CTZ Formato',
            },
        ),
    ]
