# Generated by Django 4.2.7 on 2025-11-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0018_ctzformatodetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctzformatodetalle',
            name='concepto',
            field=models.TextField(blank=True, default='', verbose_name='Concepto CTZ'),
        ),
    ]
