# Generated by Django 4.2.7 on 2025-11-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0019_ctzformatodetalle_concepto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctzformatodetalle',
            name='unidad',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Unidad CTZ'),
        ),
    ]
