# Generated by Django 4.2.7 on 2025-11-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0020_ctzformatodetalle_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctzformato',
            name='fecha_manual',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
    ]
