# Generated by Django 4.2.7 on 2025-11-27 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0021_ctzformato_fecha_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctzformato',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formatos', to='empresas.contacto', verbose_name='Contacto'),
        ),
    ]
