# Generated by Django 4.2.7 on 2025-11-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0022_ctzformato_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctzformato',
            name='notas_observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Notas / Observaciones'),
        ),
        migrations.AddField(
            model_name='ctzformato',
            name='propuesta_redaccion',
            field=models.TextField(blank=True, null=True, verbose_name='Propuesta Redacción'),
        ),
    ]
