# Generated by Django 4.2.7 on 2025-12-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0023_ctzformato_notas_observaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctzformatodetalle',
            name='concepto',
        ),
        migrations.AddField(
            model_name='ctz',
            name='concepto',
            field=models.TextField(blank=True, default='', verbose_name='Concepto'),
        ),
    ]
