# Generated by Django 4.2.7 on 2025-12-16 01:53

from django.db import migrations
from django.utils import timezone


def fill_fecha_field(apps, schema_editor):
    """Llenar el campo fecha con fecha_creacion::date si está vacío"""
    CTZFormato = apps.get_model('empresas', 'CTZFormato')
    today = timezone.now().date()
    for obj in CTZFormato.objects.filter(fecha__isnull=True):
        obj.fecha = today
        obj.save(update_fields=['fecha'])


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0024_remove_ctzformatodetalle_concepto'),
    ]

    operations = [
        migrations.RunPython(fill_fecha_field),
    ]
