# Generated by Django 4.2.7 on 2025-12-16 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0024_remove_ctzformatodetalle_concepto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctzformato',
            name='fecha',
        ),
    ]
