# Generated by Django 4.2.7 on 2025-12-16 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0025_drop_fecha_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTZFormatoMPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obra', models.CharField(max_length=200, verbose_name='Obra (Trabajos a ejecutar)')),
                ('departamento', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('importe_contacto', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Importe de Contacto')),
                ('anticipo_solicitado', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Anticipo Solicitado')),
                ('moneda', models.CharField(choices=[('MXN', 'Pesos Mexicanos (MXN)'), ('USD', 'Dólares Estadounidenses (USD)'), ('EUR', 'Euros (EUR)')], default='MXN', max_length=3, verbose_name='Moneda')),
                ('mano_de_obra', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Mano de Obra')),
                ('materiales', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Materiales')),
                ('tiempo_ejecucion_valor', models.IntegerField(default=1, verbose_name='Tiempo de Ejecución (valor)')),
                ('tiempo_ejecucion_unidad', models.CharField(choices=[('semanas', 'Semanas'), ('meses', 'Meses')], default='semanas', max_length=10, verbose_name='Unidad de Tiempo')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ctzs', models.ManyToManyField(blank=True, related_name='formatos_mpa', to='empresas.ctz', verbose_name='CTZs')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formatos_mpa', to='empresas.contacto', verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'CTZ Formato MPA',
                'verbose_name_plural': 'CTZs Formato MPA',
            },
        ),
    ]
