# Generated by Django 4.2.7 on 2025-12-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0026_ctzformatompa'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameField(
                    model_name='ctzformatompa',
                    old_name='importe_contacto',
                    new_name='importe_contrato',
                ),
                migrations.AlterField(
                    model_name='ctzformatompa',
                    name='importe_contrato',
                    field=models.DecimalField(
                        db_column='importe_contacto',
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name='Importe de Contrato',
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='ctzformatompa',
            name='edificio',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Edificio'),
        ),
        migrations.AddField(
            model_name='ctzformatompa',
            name='fecha_elaboracion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elaboración'),
        ),
        migrations.AddField(
            model_name='ctzformatompa',
            name='proveedor',
            field=models.CharField(blank=True, default='Servicios Industriales SOMA', max_length=150, verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='ctzformatompa',
            name='suite',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Suite'),
        ),
    ]
