# Generated by Django 4.2.7 on 2025-12-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0027_remove_ctzformatompa_importe_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctzformatompa',
            name='anticipo_solicitado',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Anticipo Solicitado'),
        ),
        migrations.AlterField(
            model_name='ctzformatompa',
            name='mano_de_obra',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Mano de Obra'),
        ),
        migrations.AlterField(
            model_name='ctzformatompa',
            name='materiales',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Materiales'),
        ),
    ]
