# Generated by Django 4.2.7 on 2025-12-16 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0028_alter_ctzformatompa_anticipo_solicitado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTZFormatoMPADetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('pu', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unidad', models.CharField(blank=True, default='', max_length=30, verbose_name='Unidad')),
                ('ctz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.ctz')),
                ('formato_mpa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='empresas.ctzformatompa')),
            ],
            options={
                'verbose_name': 'Detalle CTZ Formato MPA',
                'verbose_name_plural': 'Detalles CTZ Formato MPA',
            },
        ),
    ]
