# Generated by Django 4.2.7 on 2025-12-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0029_ctzformatompadetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctzformatompa',
            name='tiempo_ejecucion_unidad',
            field=models.CharField(choices=[('semanas', 'Semanas'), ('meses', 'Meses'), ('no_aplica', 'NO APLICA')], default='semanas', max_length=10, verbose_name='Unidad de Tiempo'),
        ),
        migrations.AlterField(
            model_name='ctzformatompa',
            name='tiempo_ejecucion_valor',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Tiempo de Ejecución (valor)'),
        ),
    ]
