# Generated by Django 4.2.7 on 2025-09-25 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recursos_humanos', '0005_delete_contrato_delete_tipocontrato'),
        ('empresas', '0006_alter_contacto_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de asignación')),
                ('detalles', models.TextField(verbose_name='Detalles de la asignación')),
                ('completada', models.BooleanField(default=False, verbose_name='Completada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='recursos_humanos.empleado', verbose_name='Empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='empresas.empresa', verbose_name='Empresa')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_supervisadas', to='recursos_humanos.empleado', verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'ordering': ['-fecha', 'empleado__numero_empleado'],
                'indexes': [models.Index(fields=['fecha', 'empleado'], name='asignacione_fecha_164e02_idx')],
                'unique_together': {('fecha', 'empleado', 'empresa', 'detalles')},
            },
        ),
    ]
