# Generated by Django 4.2.7 on 2025-09-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0005_delete_contrato_delete_tipocontrato'),
        ('asignaciones', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Solo cambia el estado del modelo para reflejar el nuevo unique_together
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='asignacion',
                    unique_together={('fecha', 'empleado')},
                ),
            ],
            # En la base de datos, añade una UniqueConstraint explícita para (fecha, empleado)
            database_operations=[
                migrations.AddConstraint(
                    model_name='asignacion',
                    constraint=models.UniqueConstraint(
                        fields=['fecha', 'empleado'], name='unique_asignacion_fecha_empleado'
                    ),
                ),
            ],
        ),
    ]
