# Generated by Django 4.2.7 on 2025-09-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0006_puesto_superior'),
        ('asignaciones', '0008_drop_creado_actualizado_if_exists'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Asignación', 'verbose_name_plural': 'Asignaciones'},
        ),
        migrations.RemoveIndex(
            model_name='asignacion',
            name='asignacione_fecha_164e02_idx',
        ),
        migrations.AlterUniqueTogether(
            name='asignacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='empleados',
            field=models.ManyToManyField(related_name='asignaciones', to='recursos_humanos.empleado', verbose_name='Empleados'),
        ),
        migrations.AddIndex(
            model_name='asignacion',
            index=models.Index(fields=['fecha'], name='asignacione_fecha_97ec8c_idx'),
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='empleado',
        ),
    ]
