# Generated by Django 4.2.7 on 2025-09-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0009_alter_asignacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='archivos',
            field=models.FileField(blank=True, null=True, upload_to='asignaciones/archivos/', verbose_name='Archivos adjuntos'),
        ),
    ]
