# Generated by Django 4.2.7 on 2025-09-30 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0010_asignacion_archivos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadAsignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Actividad')),
                ('porcentaje', models.PositiveIntegerField(verbose_name='Porcentaje')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='asignaciones.asignacion')),
            ],
            options={
                'verbose_name': 'Actividad asignada',
                'verbose_name_plural': 'Actividades asignadas',
            },
        ),
    ]
