# Generated by Django 4.2.7 on 2025-10-02 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0006_puesto_superior'),
        ('asignaciones', '0011_actividadasignada'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadasignada',
            name='completada',
            field=models.BooleanField(default=False, verbose_name='Completada'),
        ),
        migrations.AddField(
            model_name='actividadasignada',
            name='completada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos_humanos.empleado', verbose_name='Completada por'),
        ),
        migrations.AddField(
            model_name='actividadasignada',
            name='fecha_completada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
    ]
