# Generated by Django 4.2.7 on 2025-10-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0012_actividadasignada_completada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadasignada',
            name='tiempo_estimado_dias',
            field=models.PositiveIntegerField(default=1, verbose_name='Tiempo estimado (días)'),
        ),
    ]
