# Generated by Django 4.2.7 on 2025-10-30 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0012_alter_empleado_activo_alter_empleado_numero_empleado'),
        ('asignaciones', '0013_actividadasignada_tiempo_estimado_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='numero_cotizacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='No. cotización'),
        ),
        migrations.CreateModel(
            name='HistorialSupervisorAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_supervisores', to='asignaciones.asignacion')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos_humanos.empleado')),
            ],
            options={
                'verbose_name': 'Historial de Supervisor',
                'verbose_name_plural': 'Historial de Supervisores',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEmpleadoAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('agregado', 'Agregado'), ('removido', 'Removido')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_empleados', to='asignaciones.asignacion')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos_humanos.empleado')),
            ],
            options={
                'verbose_name': 'Historial de Empleado',
                'verbose_name_plural': 'Historial de Empleados',
                'ordering': ['-timestamp'],
            },
        ),
    ]
