# Generated by Django 4.2.7 on 2025-10-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0014_asignacion_numero_cotizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='numero_cotizacion_int',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='No. cotización (num)'),
        ),
    ]
