# Generated by manual edit to consolidate numero_cotizacion fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0015_asignacion_numero_cotizacion_int'),
    ]

    operations = [
        # Eliminar el campo char agregado por la migración anterior
        migrations.RemoveField(
            model_name='asignacion',
            name='numero_cotizacion',
        ),
        # Renombrar el campo entero intermedio al nombre definitivo
        migrations.RenameField(
            model_name='asignacion',
            old_name='numero_cotizacion_int',
            new_name='numero_cotizacion',
        ),
        # Asegurar las propiedades (verbose_name, null/blank)
        migrations.AlterField(
            model_name='asignacion',
            name='numero_cotizacion',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='No. cotización'),
        ),
    ]
