# Generated by Django 4.2.7 on 2025-11-05 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0012_alter_empleado_activo_alter_empleado_numero_empleado'),
        ('asignaciones', '0016_consolidate_numero_cotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialempleadoasignacion',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos_humanos.empleado', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='historialsupervisorasignacion',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos_humanos.empleado', verbose_name='Supervisor'),
        ),
    ]
