# Generated by Django 4.2.7 on 2025-11-11 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0017_alter_historialempleadoasignacion_empleado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='fecha_termino',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de término'),
        ),
        migrations.CreateModel(
            name='AsignacionDiaTrabajado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha trabajada')),
                ('notas', models.CharField(blank=True, max_length=255, null=True, verbose_name='Notas (opcional)')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_trabajados', to='asignaciones.asignacion')),
            ],
            options={
                'verbose_name': 'Día trabajado',
                'verbose_name_plural': 'Días trabajados',
                'ordering': ['-fecha'],
                'unique_together': {('asignacion', 'fecha')},
            },
        ),
    ]
