# Generated by Django 4.2.7 on 2025-09-22 17:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del puesto')),
                ('descripcion', models.TextField(verbose_name='Descripción del puesto')),
                ('salario_minimo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario mínimo')),
                ('salario_maximo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario máximo')),
                ('requisitos', models.TextField(blank=True, verbose_name='Requisitos')),
                ('activo', models.BooleanField(default=True, verbose_name='Puesto activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Tipo de contrato')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de contrato',
                'verbose_name_plural': 'Tipos de contrato',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_empleado', models.CharField(max_length=20, unique=True, verbose_name='Número de empleado')),
                ('curp', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{4}[0-9]{6}[HM][A-Z]{5}[0-9]{2}$', 'CURP inválida')], verbose_name='CURP')),
                ('rfc', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^[A-Z&Ñ]{3,4}[0-9]{6}[A-Z0-9]{3}$', 'RFC inválido')], verbose_name='RFC')),
                ('nss', models.CharField(blank=True, max_length=11, verbose_name='Número de Seguro Social')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('estado_civil', models.CharField(choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('divorciado', 'Divorciado/a'), ('viudo', 'Viudo/a'), ('union_libre', 'Unión libre')], max_length=15, verbose_name='Estado civil')),
                ('tipo_sangre', models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, verbose_name='Tipo de sangre')),
                ('telefono_personal', models.CharField(max_length=15, verbose_name='Teléfono personal')),
                ('telefono_emergencia', models.CharField(max_length=15, verbose_name='Teléfono de emergencia')),
                ('contacto_emergencia', models.CharField(max_length=100, verbose_name='Contacto de emergencia')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('motivo_baja', models.TextField(blank=True, verbose_name='Motivo de baja')),
                ('salario_actual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario actual')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='empleados/fotos/', verbose_name='Fotografía')),
                ('activo', models.BooleanField(default=True, verbose_name='Empleado activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.departamento', verbose_name='Departamento')),
                ('jefe_directo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos_humanos.empleado', verbose_name='Jefe directo')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursos_humanos.puesto', verbose_name='Puesto')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['numero_empleado'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Contrato activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='recursos_humanos.empleado')),
                ('tipo_contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recursos_humanos.tipocontrato', verbose_name='Tipo de contrato')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
