# Generated by Django 4.2.7 on 2025-09-24 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('recursos_humanos', '0002_empleado_sexo_alter_empleado_rfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empresas.departamento', verbose_name='Departamento'),
        ),
    ]
