# Generated by Django 4.2.7 on 2025-09-24 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0003_alter_empleado_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='departamento',
        ),
    ]
