# Generated by Django 4.2.7 on 2025-09-24 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0004_remove_empleado_departamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contrato',
        ),
        migrations.DeleteModel(
            name='TipoContrato',
        ),
    ]
