# Generated by Django 4.2.7 on 2025-09-25 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0005_delete_contrato_delete_tipocontrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='superior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puestos_subordinados', to='recursos_humanos.puesto', verbose_name='Puesto supervisor'),
        ),
    ]
