# Generated by Django 4.2.7 on 2025-10-15 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0006_puesto_superior'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoEstatusEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('vacaciones', 'Vacaciones'), ('incapacidad', 'Incapacidad')], max_length=20, verbose_name='Estatus laboral')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio del estatus')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin del estatus')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_estatus', to='recursos_humanos.empleado')),
            ],
            options={
                'verbose_name': 'Periodo de estatus de empleado',
                'verbose_name_plural': 'Periodos de estatus de empleados',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
