# Generated by Django 4.2.7 on 2025-10-16 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recursos_humanos', '0007_periodoestatusempleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inasistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la inasistencia')),
                ('tipo', models.CharField(choices=[('inasistencia', 'Inasistencia'), ('permiso', 'Permiso'), ('retardo', 'Retardo')], default='inasistencia', max_length=20)),
                ('dias', models.IntegerField(default=1, verbose_name='Días')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inasistencias', to='recursos_humanos.empleado')),
                ('registrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrada por')),
            ],
            options={
                'verbose_name': 'Inasistencia',
                'verbose_name_plural': 'Inasistencias',
                'ordering': ['-fecha'],
                'unique_together': {('empleado', 'fecha')},
            },
        ),
    ]
