# Generated by Django 4.2.7 on 2025-10-16 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_contacto_fecha_nacimiento'),
        ('recursos_humanos', '0010_add_fk_registrada_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inasistencia',
            name='dias',
        ),
        migrations.RemoveField(
            model_name='inasistencia',
            name='registrada_por',
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=30, unique=True, verbose_name='No. contrato')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_termino', models.DateField(verbose_name='Fecha de término')),
                ('periodo_ejecucion', models.CharField(blank=True, max_length=100, verbose_name='Periodo de ejecución')),
                ('cantidad_empleados', models.PositiveIntegerField(verbose_name='Cantidad de empleados')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionPorTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='recursos_humanos.contrato', verbose_name='No. contrato')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_contrato', to='recursos_humanos.empleado', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Asignación por trabajador',
                'verbose_name_plural': 'Asignaciones por trabajador',
                'unique_together': {('contrato', 'empleado')},
            },
        ),
    ]
