# Generated by Django 4.2.7 on 2025-10-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0011_remove_inasistencia_dias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='ACTIVO'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numero_empleado',
            field=models.CharField(max_length=20, unique=True, verbose_name='NO. empleado'),
        ),
    ]
