# Generated by Django 4.2.7 on 2025-11-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0017_alter_historialempleadoasignacion_empleado_and_more'),
        ('recursos_humanos', '0012_alter_empleado_activo_alter_empleado_numero_empleado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'CONTRATO REPSE', 'verbose_name_plural': 'CONTRATOS REPSE'},
        ),
        migrations.AddField(
            model_name='contrato',
            name='asignaciones_vinculadas',
            field=models.ManyToManyField(blank=True, related_name='contratos', to='asignaciones.asignacion', verbose_name='No. cotización (Asignaciones)'),
        ),
    ]
