# Generated by Django 4.2.7 on 2025-11-07 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0013_alter_contrato_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Contratos REPSE', 'verbose_name_plural': 'Contratos REPSE'},
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='periodo_ejecucion',
        ),
    ]
