# Generated by Django 4.2.7 on 2025-11-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0014_alter_contrato_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='dias_activos',
            field=models.PositiveIntegerField(default=0, verbose_name='Días activos'),
        ),
    ]
