# Generated by Django 4.2.7 on 2025-11-11 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_alter_empresa_activa_alter_empresa_nombre'),
        ('recursos_humanos', '0015_contrato_dias_activos'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionportrabajador',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_por_trabajador', to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='asignacionportrabajador',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Periodo inicio'),
        ),
        migrations.AddField(
            model_name='asignacionportrabajador',
            name='fecha_termino',
            field=models.DateField(blank=True, null=True, verbose_name='Periodo término'),
        ),
        migrations.AddField(
            model_name='asignacionportrabajador',
            name='nss',
            field=models.CharField(blank=True, max_length=11, verbose_name='NSS'),
        ),
    ]
