# Generated by Django 4.2.7 on 2025-11-12 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0016_asignacionportrabajador_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='salario_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Salario inicial'),
        ),
        migrations.CreateModel(
            name='CambioSalarioEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('salario_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salario_nuevo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_salario', to='recursos_humanos.empleado')),
            ],
            options={
                'verbose_name': 'Cambio de salario de empleado',
                'verbose_name_plural': 'Historial de cambios de salario',
                'ordering': ['-fecha'],
            },
        ),
    ]
