# Generated by Django 4.2.7 on 2025-11-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0017_empleado_salario_inicial_cambiosalarioempleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodoestatusempleado',
            name='notificado_fin',
            field=models.BooleanField(default=False, verbose_name='Notificado fin de periodo'),
        ),
    ]
