# Generated by Django 4.2.7 on 2025-11-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0018_periodoestatusempleado_notificado_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='lugar_de_pertenencia',
            field=models.CharField(blank=True, choices=[('GDL', 'GDL'), ('QRO', 'QRO'), ('CDMX', 'CDMX'), ('EDO_MEX', 'EDO MEX')], max_length=20, null=True, verbose_name='Lugar de pertenencia'),
        ),
    ]
