# Generated by Django 4.2.7 on 2025-11-13 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraseAdministradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='Texto que se mostrará encima del login y en perfiles de empleado', verbose_name='Frase')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frases_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Frase de administradores',
                'verbose_name_plural': 'Frases de administradores',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
