# Generated by Django 4.2.7 on 2025-10-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0006_transferenciaherramienta_inspeccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferenciaherramienta',
            name='estado',
            field=models.CharField(choices=[('solicitada', 'Solicitada'), ('inspeccion', 'En Inspección'), ('inspeccion_enviada', 'Inspección Enviada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='solicitada', max_length=20),
        ),
    ]
