# Generated by Django 4.2.7 on 2025-11-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0007_alter_transferenciaherramienta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='lugar_pertenencia',
            field=models.CharField(choices=[('GDL', 'GDL'), ('MEX', 'MEX'), ('CDMX', 'CDMX'), ('QRO', 'QRO')], default='GDL', max_length=4, verbose_name='Lugar de pertenencia'),
            preserve_default=False,
        ),
    ]
