# Generated by Django 4.2.7 on 2025-12-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0008_herramienta_lugar_pertenencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='tipo',
            field=models.CharField(choices=[('MAQ', 'Maquinaria'), ('EQU', 'Equipo'), ('HER', 'Herramienta')], default='HER', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='uso_energia',
            field=models.CharField(blank=True, choices=[('gasolina', 'Gasolina'), ('diesel', 'Diésel'), ('luz', 'Luz (eléctrico)'), ('gas', 'Gas'), ('otro', 'Otro')], help_text='Habilitado solo si Tipo = Maquinaria', max_length=20, null=True, verbose_name='Uso combustible/energía'),
        ),
    ]
