# Generated by Django 4.2.7 on 2025-12-02 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0019_empleado_lugar_de_pertenencia'),
        ('herramientas', '0009_herramienta_tipo_herramienta_uso_energia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombustibleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='herramientas/combustible/')),
                ('observaciones', models.TextField(blank=True)),
                ('monto_comprobado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado'), ('rechazado', 'Rechazado'), ('parcial', 'Parcialmente comprobado'), ('comprobado', 'Comprobante completo')], default='pendiente', max_length=20)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.empleado')),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herramientas.herramienta')),
            ],
            options={
                'verbose_name': 'Solicitud de Combustible',
                'verbose_name_plural': 'Solicitudes de Combustible',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CombustibleComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='herramientas/combustible/historial/')),
                ('original_name', models.CharField(blank=True, max_length=255, null=True)),
                ('notas', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('combustible_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='herramientas.combustiblerequest')),
            ],
            options={
                'verbose_name': 'Comprobante Combustible',
                'verbose_name_plural': 'Comprobantes Combustible',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
