# Generated by Django 4.2.7 on 2025-09-22 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recursos_humanos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('placas', models.CharField(max_length=10, unique=True)),
                ('numero_serie', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('sedan', 'Sedán'), ('camioneta', 'Camioneta'), ('motocicleta', 'Motocicleta'), ('camion', 'Camión')], max_length=20)),
                ('kilometraje_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('asignado', 'Asignado'), ('mantenimiento', 'Mantenimiento'), ('baja', 'Baja')], default='disponible', max_length=20)),
                ('fecha_adquisicion', models.DateField()),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('tarjeta_circulacion', models.FileField(blank=True, null=True, upload_to='vehiculos/documentos/')),
                ('tenencia', models.DateField(blank=True, null=True)),
                ('verificacion_vehicular', models.DateField(blank=True, null=True)),
                ('seguro', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
        migrations.CreateModel(
            name='TransferenciaVehicular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_transferencia', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('inspeccion', 'En Inspección'), ('observaciones', 'Con Observaciones'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('completada', 'Completada')], default='solicitada', max_length=20)),
                ('kilometraje_transferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones_solicitud', models.TextField(blank=True)),
                ('observaciones_inspeccion', models.TextField(blank=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_aprobadas', to='recursos_humanos.empleado')),
                ('empleado_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_destino', to='recursos_humanos.empleado')),
                ('empleado_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_origen', to='recursos_humanos.empleado')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flota_vehicular.vehiculo')),
            ],
            options={
                'verbose_name': 'Transferencia Vehicular',
                'verbose_name_plural': 'Transferencias Vehiculares',
            },
        ),
        migrations.CreateModel(
            name='RegistroUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('kilometraje_inicio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kilometraje_fin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('destino', models.CharField(max_length=200)),
                ('proposito', models.TextField()),
                ('observaciones', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.empleado')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flota_vehicular.vehiculo')),
            ],
            options={
                'verbose_name': 'Registro de Uso',
                'verbose_name_plural': 'Registros de Uso',
            },
        ),
        migrations.CreateModel(
            name='AsignacionVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('finalizada', 'Finalizada'), ('pendiente', 'Pendiente')], default='activa', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.empleado')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flota_vehicular.vehiculo')),
            ],
            options={
                'verbose_name': 'Asignación de Vehículo',
                'verbose_name_plural': 'Asignaciones de Vehículos',
            },
        ),
    ]
