# Generated by Django 4.2.7 on 2025-09-26 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flota_vehicular', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='fecha_adquisicion',
        ),
    ]
