# Generated by Django 4.2.7 on 2025-09-26 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flota_vehicular', '0002_remove_vehiculo_fecha_adquisicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='tenencia',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='verificacion_vehicular',
        ),
        migrations.CreateModel(
            name='VerificacionVehicular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_verificacion', models.CharField(choices=[('primera', 'Primera Verificación'), ('segunda', 'Segunda Verificación'), ('extraordinaria', 'Verificación Extraordinaria')], max_length=20)),
                ('fecha_verificacion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('numero_certificado', models.CharField(max_length=50, unique=True)),
                ('centro_verificacion', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('pendiente', 'Pendiente'), ('vencida', 'Vencida')], default='pendiente', max_length=20)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('certificado', models.FileField(blank=True, null=True, upload_to='vehiculos/verificaciones/')),
                ('observaciones', models.TextField(blank=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificaciones', to='flota_vehicular.vehiculo')),
            ],
            options={
                'verbose_name': 'Verificación Vehicular',
                'verbose_name_plural': 'Verificaciones Vehiculares',
                'ordering': ['-fecha_verificacion'],
            },
        ),
        migrations.CreateModel(
            name='TenenciaVehicular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año_fiscal', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('folio', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('vencida', 'Vencida'), ('pendiente', 'Pendiente de Pago'), ('exenta', 'Exenta')], default='pendiente', max_length=20)),
                ('comprobante_pago', models.FileField(blank=True, null=True, upload_to='vehiculos/tenencias/')),
                ('observaciones', models.TextField(blank=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenencias', to='flota_vehicular.vehiculo')),
            ],
            options={
                'verbose_name': 'Tenencia Vehicular',
                'verbose_name_plural': 'Tenencias Vehiculares',
                'ordering': ['-año_fiscal'],
                'unique_together': {('vehiculo', 'año_fiscal')},
            },
        ),
    ]
