# Generated by Django 4.2.7 on 2025-09-26 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flota_vehicular', '0003_remove_vehiculo_costo_remove_vehiculo_tenencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='seguro',
        ),
    ]
