# Generated by Django 4.2.7 on 2025-09-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota_vehicular', '0004_remove_vehiculo_seguro'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='aseguradora',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la aseguradora'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='contacto_aseguradora',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de contacto de la aseguradora'),
        ),
    ]
