# Generated by Django 4.2.7 on 2025-09-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota_vehicular', '0005_vehiculo_aseguradora_vehiculo_contacto_aseguradora'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='numero_seguro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de póliza de seguro'),
        ),
    ]
