# Generated by Django 4.2.7 on 2025-10-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota_vehicular', '0011_alter_transferenciavehicular_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferenciavehicular',
            name='estado',
            field=models.CharField(choices=[('solicitada', 'Solicitada'), ('inspeccion', 'En Inspección'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='solicitada', max_length=30),
        ),
    ]
