# Generated by Django 4.2.7 on 2025-10-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota_vehicular', '0012_alter_transferenciavehicular_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferenciavehicular',
            name='fecha_inspeccion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferenciavehicular',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
