# Generated by Django 4.2.7 on 2025-10-10 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flota_vehicular', '0013_transferenciavehicular_fecha_inspeccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenenciavehicular',
            name='comprobante_pago',
        ),
        migrations.RemoveField(
            model_name='tenenciavehicular',
            name='folio',
        ),
        migrations.RemoveField(
            model_name='tenenciavehicular',
            name='monto',
        ),
    ]
