# Generated by Django 4.2.7 on 2025-10-10 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flota_vehicular', '0014_remove_tenenciavehicular_comprobante_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificacionvehicular',
            name='centro_verificacion',
        ),
        migrations.RemoveField(
            model_name='verificacionvehicular',
            name='certificado',
        ),
        migrations.RemoveField(
            model_name='verificacionvehicular',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='verificacionvehicular',
            name='numero_certificado',
        ),
    ]
