# Generated by Django 4.2.7 on 2025-11-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota_vehicular', '0015_remove_verificacionvehicular_centro_verificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificacionvehicular',
            name='documento_verificacion',
            field=models.FileField(blank=True, null=True, upload_to='vehiculos/verificaciones/'),
        ),
    ]
