# Generated by Django 4.2.7 on 2025-11-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota_vehicular', '0016_verificacionvehicular_documento_verificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificacionvehicular',
            name='numero_verificacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
