# Generated by Django 4.2.7 on 2025-11-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flota_vehicular', '0017_verificacionvehicular_numero_verificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrouso',
            name='destino',
        ),
    ]
