# Generated by Django 4.2.7 on 2025-11-12 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0016_asignacionportrabajador_empresa_and_more'),
        ('flota_vehicular', '0018_remove_registrouso_destino'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placas', models.CharField(max_length=20, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('numero_seguro', models.CharField(blank=True, max_length=100, null=True, verbose_name='No. seguro')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('asignado', 'Asignado'), ('mantenimiento', 'Mantenimiento'), ('baja', 'Baja')], default='disponible', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Vehículo Externo',
                'verbose_name_plural': 'Vehículos Externos',
            },
        ),
        migrations.CreateModel(
            name='AsignacionVehiculoExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('finalizada', 'Finalizada'), ('pendiente', 'Pendiente')], default='activa', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.empleado')),
                ('vehiculo_externo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='flota_vehicular.vehiculoexterno')),
            ],
            options={
                'verbose_name': 'Asignación Vehículo Externo',
                'verbose_name_plural': 'Asignaciones Vehículos Externos',
            },
        ),
    ]
