# Generated by Django 4.2.7 on 2025-11-12 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0016_asignacionportrabajador_empresa_and_more'),
        ('flota_vehicular', '0019_vehiculoexterno_asignacionvehiculoexterno'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasolinaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprobante', models.FileField(upload_to='flota/gasolina/')),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.empleado')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flota_vehicular.vehiculo')),
                ('vehiculo_externo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flota_vehicular.vehiculoexterno')),
            ],
            options={
                'verbose_name': 'Solicitud de Gasolina',
                'verbose_name_plural': 'Solicitudes de Gasolina',
                'ordering': ['-fecha'],
            },
        ),
    ]
