# Generated by Django 4.2.7 on 2025-11-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota_vehicular', '0020_gasolinarequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasolinarequest',
            name='monto_comprobado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='gasolinarequest',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='flota/gasolina/'),
        ),
        migrations.AlterField(
            model_name='gasolinarequest',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado'), ('rechazado', 'Rechazado'), ('parcial', 'Parcialmente comprobado'), ('comprobado', 'Comprobante completo')], default='pendiente', max_length=20),
        ),
    ]
