# Generated by Django 4.2.7 on 2025-11-28 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flota_vehicular', '0021_gasolinarequest_monto_comprobado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasolinaComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='flota/gasolina/historial/')),
                ('notas', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gasolina_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='flota_vehicular.gasolinarequest')),
            ],
            options={
                'verbose_name': 'Comprobante Gasolina',
                'verbose_name_plural': 'Comprobantes Gasolina',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
