# Generated by Django 4.2.7 on 2025-11-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota_vehicular', '0022_gasolinacomprobante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gasolinacomprobante',
            options={'ordering': ['uploaded_at'], 'verbose_name': 'Comprobante Gasolina', 'verbose_name_plural': 'Comprobantes Gasolina'},
        ),
        migrations.AddField(
            model_name='gasolinacomprobante',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
