# Generated by Django 4.2.7 on 2025-12-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota_vehicular', '0023_alter_gasolinacomprobante_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenenciavehicular',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='vehiculos/tenencia/', verbose_name='Comprobante de tenencia'),
        ),
    ]
