# Generated by Django 4.2.7 on 2025-12-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota_vehicular', '0024_tenenciavehicular_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenenciavehicular',
            name='pagada',
            field=models.BooleanField(db_column='pagada', default=False),
        ),
        migrations.AlterField(
            model_name='tenenciavehicular',
            name='año_fiscal',
            field=models.IntegerField(db_column='año'),
        ),
    ]
